title: Juan S. Carrillo
email:
description: >-
  Researcher in AI for image restoration and atmospheric turbulence mitigation.
  Exploring optics, deep learning, and signal processing. 
  Previously worked on medical imaging applications, including automated analysis for glaucoma detection.

twitter_username: username
github_username: sebastiancarrillo
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Juan Carrillo"
  avatar : "/assets/images/bioPhoto.jpeg"
  bio    : "Ph.D. student in Computational Science at San Diego State University and UC Irvine, specializing in image processing and machine learning."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sebastiancarrillo.github.io/Juan-S.-Carrillo-R/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sebastiancarrillo"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/juans3b4s/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sebastiancarrillo"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/juans3b4s/"

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
      css: "/assets/css/custom.css"

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
